services:
    VulnerableApp-base:
      image: sasanlabs/owasp-vulnerableapp:latest
      
    VulnerableApp-jsp:
      image: sasanlabs/owasp-vulnerableapp-jsp:latest
 
    VulnerableApp-php:
      image: sasanlabs/owasp-vulnerableapp-php:latest
    
    VulnerableApp-facade:
      depends_on:
        - VulnerableApp-base
        - VulnerableApp-jsp
        - VulnerableApp-php
      # All services use :latest tag for consistency and easier deployment
      image: sasanlabs/owasp-vulnerableapp-facade:latest
      volumes:
       - ./templates:/etc/nginx/templates
      ports:
       - "80:80"
      environment:
       - NGINX_HOST=foobar.com
       - NGINX_PORT=80