version: "2.2"
services:
    VulnerableApp-base:
      image: sasanlabs/owasp-vulnerableapp
      ports:
       - "9090:9090"
       
    VulnerableApp-web:
      depends_on:
        - VulnerableApp-base
      image: vulnerableapp_nginx
      volumes:
       - ./templates:/etc/nginx/templates
      ports:
       - "8080:80"
      environment:
       - NGINX_HOST=foobar.com
       - NGINX_PORT=80